env:
  global:
    - DISPLAY=:99.0
    - BASEURL=http://localhost:9500
    - BROWSER_LIST="chrome firefox internet+explorer"

sudo: required

language: node_js

node_js:
  - "4.1"

services:
  - docker

addons:
  firefox: "latest"
  sauce_connect:
    no_ssl_bump_domains: all

before_script:
  - curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -
  - sh -e /etc/init.d/xvfb start

script:
  - make all

deploy:
  skip_cleanup: true
  provider: script
  script: make release
  on:
    tags: true

notifications:
  slack: cloudet:rMfRKhvsbZuCIRZpTct3kBI4#jupyter-declwidgets
  email:
    on_success: change
    on_failure: always

branches:
  only:
    - master
    - InternetExplorerTest
